<div class="dataTable_wrapper">

    
    <h2>How does it work?</h2>

<p>
To prove that neither you nor us can possibly know what will be the result of the dices, we use two different numbers, one generated from our server and the other generated by your browser (Can be edited manually if you want), the combination of this numbers will be used to create the dices result.
</p>

<h2>Details of the process</h2>

<p>Before each spin our server generates one 12 dygit number composed of 2 parts, first 6 digyts are the numbers from 1 to 6 in a random order and last 6 digyts are also the numbers from 1 to 6 in a diferent random order (<strong>SERVER #</strong>), this number is encrypted using 2 secret keys (<strong>SECRETS</strong>) and then is displayed to you (Find it at the top of your craps table). At the same time your browser generates a pair of numbers between 1 and 6 (<strong>PLAYER #</strong>) (this numbers can be edited by you, is located at the top of your craps table). At the moment you make your roll, your browser will send the <strong>PLAYER #</strong> to our server, then we will get the dice result from the  <strong>SERVER #</strong> getting the digits  on the positions defined by <strong>PLAYER #</strong>. For example, if <strong>SERVER #</strong> is 451236312654 and <strong>PLAYER #</strong> is 1,3 , the dices results will be 4 and 2 (Position 1 in the first part of <strong>PLAYER #</strong> is 4 and position 3 in the second part of <strong>PLAYER #</strong> is 2). Finally the results will be displayed, including the <strong>SECRET KEYS</strong> used to encrypt the <strong>SERVER #</strong>, the <strong>SERVER #</strong> decrypted, the <strong>PLAYER #</strong> provided by you and the <strong>FINAL NUMBER</strong> used to get the dices results, with this information you can verify that the 
<strong>SERVER #</strong> wasn't changed and that your roll result was completely random.</p>


<h3>How the SERVER # is encrypted?</h3>
<p>
The <strong>SERVER #</strong> is encrypted with the <strong>SECRET KEYS</strong> using the <strong>BCRYPT</strong> hashing function, the encryption is made in the following way: <strong>BCRYPT(SECRET1+SERVER#+SECRET2)</strong>
</p>
<h3>Example</h3>
<p>
- Before the roll you see at the <strong>NEXT ROLL</strong> area that <strong>SERVER #</strong> is <strong style="background:#9F0;">&nbsp;
$2y$10$F70wwj8tq4fNYfhLBS1KJuo7wdkmWQ.oxaF7m65M.FxZSinNB7ydS
&nbsp;</strong> and you insert <strong>1,3</strong> as the <strong>PLAYER #</strong>.</p>
<p>
- After the roll you get as a result: <strong>SECRET1</strong>: <strong style="background:#9F0;">&nbsp; RA.cL{U2vi}95SXQ?ETBr1]A298dfd@4TTFq=_OLv[oQz*un1@|Fa: &nbsp;</strong>, <strong>SECRET2</strong>: <strong style="background:#9F0;">&nbsp; x?R,w3f[8BboEqmJhUUQ9FNVSpyecwR|3Nd,j0I]}=Imof,!nqTsLy*Yh{W6rXBNYj@2e@w_ &nbsp;</strong>, <strong>SERVER #</strong>: 425316435621 , <strong>PLAYER #</strong>: 1,3, <strong>RESULT #</strong>: 4,5
</p>
<p>
- To verify that the <strong>SERVER #</strong> wasn't changed after the spin, you use any <a href="https://bcrypt-generator.com/" target="_blank">BCRYPT generator</a> and insert: 
<strong style="background:#9F0;">&nbsp; $2y$10$F70wwj8tq4fNYfhLBS1KJuo7wdkmWQ.oxaF7m65M.FxZSinNB7ydS &nbsp;</strong> (original encrypted SERVER#) as the hash to check and <strong style="background:#9F0;">&nbsp; RA.cL{U2vi}95SXQ?ETBr1]A298dfd@4TTFq=_OLv[oQz*un1@|Fa:425316435621x?R,w3f[8BboEqmJhUUQ9FNVSpyecwR|3Nd,j0I]}=Imof,!nqTsLy*Yh{W6rXBNYj@2e@w_ &nbsp;</strong> (SECRET1+SERVER#+SECRET2) as the string to check against, finally the tool will tell you both strings match, confirming that the SERVER# never changed.

</p>

<h2>What happen if I insert an Invalid PLAYER #</h2>
<p>
<strong>PLAYER #</strong> should be a pair of numbers from 1 to 6, separate by comma (Example: <strong>3,2</strong>).
</p>
<p>
If by mistake or intentionally you insert a non numeric entry or a number lower or higher than the limits as the <strong>PLAYER #</strong>, our server will use <strong>1</strong> as your <strong>PLAYER #</strong>
</p>

    
</div>