<div class="dataTable_wrapper">

	<? 
	
	$game = new _three_card_poker(0);
	?>
    
    <h2>How does it work?</h2>

<p>
To prove that neither you nor us can possibly know how the cards will be shuffle, we use two different numbers, one generated from our server and the other generated by your browser (Can be edited manually if you want), the sum of this  numbers is used to shuffle the game cards.
</p>

<h2>Details of the process</h2>

<p>Before each hand our server generates one number between 0 and 100000000 (<strong>SERVER #</strong>), this number is encrypted using 2 secret keys (<strong>SECRETS</strong>) and then is displayed to you (Find it at the top of your game table). At the same time your browser generates another number between 0 and 100000000 (<strong>PLAYER #</strong>) (this numbers can be edited by you, is located at the top of your game table). At the moment you deal, your browser will send the <strong>PLAYER #</strong> to our server, and then it will add the <strong>SERVER #</strong> to it, the final number will be used to shuffle the game cards (If the sum of both numbers is higher than 100000000 then we will subtract  100000000 to it). For example, if <strong>SERVER #</strong> is 9856214 and <strong>PLAYER #</strong> is 994122, the number used to shuffle the cards will be 10850336. Finally the results will be displayed, including the <strong>SECRET KEYS</strong> used to encrypt the <strong>SERVER #</strong>, the <strong>SERVER #</strong> decrypted, the <strong>PLAYER #</strong> provided by you and the <strong>FINAL NUMBER</strong> used to shuffle the cards, with this information you can verify that the 
<strong>SERVER #</strong> wasn't changed and that the shuffle was completely random.</p>

<h3>Cards shuffle</h3>
<p>The game uses a total of <strong><? echo $game->number_of_decks ?></strong> decks, the original deck layout is spades, hearts, diamonds, clubs from <strong>A to K</strong>. SA, S2, S3 .. SK ... HA, H2, H3 .. HK ... DA, D2, D3 .. DK ... CA, C2, C3 .. CK, and each card is repeated the number of decks, for example, for 2 decks: SA, SA, S2,S2, S3,S3 .. SK,SK ... HA,HA, H2,H2, H3,H3 .. HK,HK ... DA,DA, D2,D2, D3,D3 .. DK,DK ... CA,CA, C2,C2, C3,C3 .. CK,CK. Then we use the sum of <strong>SERVER #</strong> + <strong>PLAYER #</strong> to seed the <strong>Mersenne Twister RNG</strong> algorithm and generate a list of random numbers, finally we shuffle the cards based on the random numbers list. 
<br /><br />You can use <a href="#tool">the tool</a> at the end of this page or <a href="utilities/download/shuffle.rar">download the source code</a> to verify a shuffle with an specific seed.
</p>

<h3>How the SERVER # is encrypted?</h3>
<p>
The <strong>SERVER #</strong> is encrypted with the <strong>SECRET KEYS</strong> using the <strong>BCRYPT</strong> hashing function, the encryption is made in the following way: <strong>BCRYPT(SECRET1+SERVER#+SECRET2)</strong>
</p>
<h3>Example</h3>
<p>
- Before the spin you see at the <strong>NEXT SPIN</strong> area that <strong>SERVER #</strong> is <strong style="background:#9F0;">&nbsp;$2y$10$eBbqayfl8W2YCynLSxRaauT14AjyC1san0FZa.ZU2AXLLTceoQiRS&nbsp;</strong> and you insert <strong>4878692</strong> as the <strong>PLAYER #</strong>.</p>
<p>
- After the spin you get as a result: <strong>SECRET1</strong>: <strong style="background:#9F0;">&nbsp;JW-&_OHO776r3SO6vl!q}BJWYaqOx}z &nbsp;</strong>, <strong>SECRET2</strong>: <strong style="background:#9F0;">&nbsp;@RTswBPLvuo,S&j]C:QaTHr5Zc4rO_8Y+GZ3vnr2vRG@D&nbsp;</strong>, <strong>SERVER #</strong>: 51884909 , <strong>PLAYER #</strong>: 4878692, <strong>RESULT #</strong>: 56763601
</p>
<p>
- To verify that the <strong>SERVER #</strong> wasnt changed after the spin, you use any <a href="https://bcrypt-generator.com/" target="_blank">BCRYPT generator</a> and insert: 
<strong style="background:#9F0;">&nbsp; $2y$10$eBbqayfl8W2YCynLSxRaauT14AjyC1san0FZa.ZU2AXLLTceoQiRS &nbsp;</strong> (original encrypted SERVER#) as the hash to check and <strong style="background:#9F0;">&nbsp; JW-&_OHO776r3SO6vl!q}BJWYaqOx}z51884909@RTswBPLvuo,S&j]C:QaTHr5Zc4rO_8Y+GZ3vnr2vRG@D &nbsp;</strong> (SECRET1+SERVER#+SECRET2) as the string to check against, finally the tool will tell you both strings match, confirming that the SERVER# never changed.

</p>

<h2>What happen if I insert an Invalid PLAYER #</h2>
<p>
<strong>PLAYER #</strong> should be a number between 0 and 100000000.
</p>
<p>
If by mistake or intentionally you insert a non numeric entry or a number lower or higher than the limits as the <strong>PLAYER #</strong>, our server will use <strong>0</strong> as your <strong>PLAYER #</strong>
</p>


<hr />

<h2>Shuffle Tool</h2>
<a href="utilities/download/shuffle.rar">Download the source code</a>
<a id="tool" name="tool"></a>

<p>
<form method="post" action="#tool">
Seed: <input name="seed" type="text" /> <input name="shuffle" type="submit" value="Shuffle" />
</form>
</p>

<p>
<?
if(param("shuffle") != ""){
	$seed = param("seed");
	if(is_numeric($seed) && $seed >= 0 && $seed <= 100000000){
		
		?> <strong>Shuffled with seed <? echo $seed ?>:</strong><br /><br /> <?
		
		$cards = prepare_decks($game->number_of_decks);
		$cards = seed_shuffle($cards,$seed);
		
		echo prepare_hand(implode(",",$cards));
		
		
	}else{
		echo "Invalid Seed, seed must be a number between 0 and 100000000";	
	}
}
?>
</p>



    
</div>