<div class="dataTable_wrapper">

	<? 
	
	$slot = new classic_slot(0);
	$slot->load_reels_content();
	?>
    
    <h2>How does it work?</h2>
<p>
First of all you need to know that we have <a href="#result_table">a table of possible results</a> for each reel, that means that every time you spin, randomly we choose one of the results in this table.</p><p>* This table will not change so each position of the table will always have the same result.
</p>

<p>
To prove that neither you nor us can possibly know what position of the table will be choose to get a result, we use two different numbers, one generated from our server and the other generated by your browser (Can be edited manually if you want), the sum of this two numbers is used to get a result from the <a href="#result_table">results table</a>.
</p>

<h2>Details of the process</h2>

<p>Before each spin our server generates a random number between 1.000.000 and 1.999.999 (<strong>SERVER #</strong>), this number is encrypted using 2 secret keys (<strong>SECRETS</strong>) and then is displayed to you (Find it at the top of your slot machine). At the same time your browser generates another random number between 1.000.000 and 1.999.999 (<strong>PLAYER #</strong>) (this number can be edited by you, is located at the top of your slot machine). At the moment you make your spin, your browser will send the <strong>PLAYER #</strong> to our server, and then it will add the <strong>SERVER #</strong> to it, the final number will be used to get a result from the <a href="#result_table">results table</a> in the following way: last 6 digits will determine the 3 reels positions, for example the number <strong>1571609</strong> will get position <strong>57</strong> for reel 1, position <strong>16</strong> for reel 2 and position <strong>09</strong> for reel 3. Finally spin results will be displayed, including the <strong>SECRET KEYS</strong> used to encrypt the <strong>SERVER #</strong>, the <strong>SERVER #</strong> decrypted, the <strong>PLAYER #</strong> provided by you and the <strong>FINAL POSITION</strong> used to get the result, with this information you can verify that the 
<strong>SERVER #</strong> wasn't changed and that your spin result was completely random.</p>

<h3>How the SERVER # is encrypted?</h3>
<p>
The <strong>SERVER #</strong> is encrypted with the <strong>SECRET KEYS</strong> using the <strong>BCRYPT</strong> hashing function, the encryption is made in the following way: <strong>BCRYPT(SECRET1+SERVER#+SECRET2)</strong>
</p>
<h3>Example</h3>
<p>
- Before the spin you see at the <strong>NEXT SPIN</strong> area that <strong>SERVER #</strong> is <strong style="background:#9F0;">&nbsp;$2y$10$x08g2e4AQcxzoKF/W6eU0uDb3mzuR9/.qhZoYWw3790vTwY8cE3wm&nbsp;</strong> and you insert <strong>1257496</strong> as the <strong>PLAYER #</strong>.</p>
<p>
- After the spin you get as a result: <strong>SECRET1</strong>: <strong style="background:#9F0;">&nbsp;(lF.g}?t4OMF)}xhK7Tmo&MR=mv&S4O &nbsp;</strong>, <strong>SECRET2</strong>: <strong style="background:#9F0;">&nbsp;JZs)k%,MiE%8h_bIwZFOd5vy;2H/Mko&nbsp;</strong>, <strong>SERVER #</strong>: 1185960, <strong>PLAYER #</strong>: 1257496, <strong>RESULT #</strong>: 2443456
</p>
<p>
- To verify that the <strong>SERVER #</strong> wasnt changed after the spin, you use any <a href="https://bcrypt-generator.com/" target="_blank">BCRYPT generator</a> and insert: 
<strong style="background:#9F0;">&nbsp;$2y$10$x08g2e4AQcxzoKF/W6eU0uDb3mzuR9/.qhZoYWw3790vTwY8cE3wm&nbsp;</strong> (original encrypted SERVER#) as the hash to check and <strong style="background:#9F0;">&nbsp;(lF.g}?t4OMF)}xhK7Tmo&MR=mv&S4O1185960JZs)k%,MiE%8h_bIwZFOd5vy;2H/Mko&nbsp;</strong> (SECRET1+SERVER#+SECRET2) as the string to check against, finally the tool will tell you both strings match, confirming that the SERVER# never changed.

</p>
<p>
Finally you sum the <strong>SERVER #</strong> and the <strong>PLAYER #</strong>, 1185960 + 1257496 = <strong>2443456</strong>, and check the <a href="#result_table">results table</a> to confirm that the position <strong>44</strong> in reel 1, position <strong>34</strong> in reel 2 and position <strong>56</strong> in reel 3 are the same result you got on the slot machine.
</p>

<h2>What happen if I insert an Invalid PLAYER #</h2>
<p>
<strong>PLAYER #</strong> should be a integer number between 1.000.000 and 1.999.999
</p>
<p>
If by mistake or intentionally you insert a non numeric entry or a number lower or higher than the limits as the <strong>PLAYER #</strong>, our server will use <strong>1.000.000</strong> as your <strong>PLAYER #</strong>
</p>

<h2>*DOES THE RESULTS TABLE EVER CHANGE?</h2>
<p>
The <strong>RESULTS TABLE</strong> is not meant to change, you can store a local copy of the <a href="#result_table">Results Table</a> to constantly verify that it haven't change.
</p>
<p>
However, it could be possible that we have to make some adjustments on the <strong>RESULTS TABLE</strong>, in this case, we will notify players in advance.
</p>


	<h2>Results Table <a id="result_table" name="result_table"></a> </h2>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Reel</th>
                <th>Position</th>
                <th>Symbol</th>
            </tr>
        </thead>
        <tbody>
            <? $i=1; $rnum = 1; foreach($slot->reels_content as $reel){ $i++; if($i%2){$class = "odd";}else{$class = "even";} ?>
				<? $pos = 0; foreach($reel as $symbol){ ?>
                    <tr class="<? echo $class ?>">
                        <td><? echo $rnum ?></td>
                        <td><? echo $pos ?></td>
                        <td><img src="https://play.casinogamesonline.com/utilities/images/web/reel/<? echo $symbol ?>.png" width="20" height="20"></td>
                    </tr>
                <? $pos++; } $rnum++; ?>
            <? } ?>
            
        </tbody>
    </table>
    
</div>