<div class="dataTable_wrapper">

    
    <h2>How does it work?</h2>

<p>
To prove that neither you nor us can possibly know what will be the result of the roulette, we use two different numbers, one generated from our server and the other generated by your browser (Can be edited manually if you want), the sum of this  numbers is used to get the roulette winning number.
</p>

<h2>Details of the process</h2>

<p>Before each spin our server generates one number between 0 and 37 (<strong>SERVER #</strong>), this number is encrypted using 2 secret keys (<strong>SECRETS</strong>) and then is displayed to you (Find it at the top of your roulette table). At the same time your browser generates another number between 0 and 37 (<strong>PLAYER #</strong>) (this numbers can be edited by you, is located at the top of your roulette table). At the moment you make your spin, your browser will send the <strong>PLAYER #</strong> to our server, and then it will add the <strong>SERVER #</strong> to it, the final number will be the winning number in the roulette (If the sum of both numbers is higher than 37 then we will subtract  37 to it). For example, if <strong>SERVER #</strong> is 10 and <strong>PLAYER #</strong> is 17, the winning number will be 27, in another example, if <strong>SERVER #</strong> is 22 and <strong>PLAYER #</strong> is 30, the winning number will be 15 (22+30=52, 52-37=15). Finally the results will be displayed, including the <strong>SECRET KEYS</strong> used to encrypt the <strong>SERVER #</strong>, the <strong>SERVER #</strong> decrypted, the <strong>PLAYER #</strong> provided by you and the <strong>FINAL NUMBER</strong> used to get the winning number, with this information you can verify that the 
<strong>SERVER #</strong> wasn't changed and that your roulette result was completely random.</p>

<p>*37 will be used as 00 in the final result</p>

<h3>How the SERVER # is encrypted?</h3>
<p>
The <strong>SERVER #</strong> is encrypted with the <strong>SECRET KEYS</strong> using the <strong>BCRYPT</strong> hashing function, the encryption is made in the following way: <strong>BCRYPT(SECRET1+SERVER#+SECRET2)</strong>
</p>
<h3>Example</h3>
<p>
- Before the spin you see at the <strong>NEXT SPIN</strong> area that <strong>SERVER #</strong> is <strong style="background:#9F0;">&nbsp;$2y$10$HP8ktjEKdHN2BpYxet6PF.3lsgNMEXqrbX6BmChiDHAtYLUK.i4O6&nbsp;</strong> and you insert <strong>12</strong> as the <strong>PLAYER #</strong>.</p>
<p>
- After the spin you get as a result: <strong>SECRET1</strong>: <strong style="background:#9F0;">&nbsp;W5xo#0CKN6$T4Gy_w8;CeU.rr)#e &nbsp;</strong>, <strong>SECRET2</strong>: <strong style="background:#9F0;">&nbsp;4UVY8Yl]n{e3H1T:W&nbsp;</strong>, <strong>SERVER #</strong>: 27 , <strong>PLAYER #</strong>: 12, <strong>RESULT #</strong>: 2
</p>
<p>
- To verify that the <strong>SERVER #</strong> wasnt changed after the spin, you use any <a href="https://bcrypt-generator.com/" target="_blank">BCRYPT generator</a> and insert: 
<strong style="background:#9F0;">&nbsp;$2y$10$HP8ktjEKdHN2BpYxet6PF.3lsgNMEXqrbX6BmChiDHAtYLUK.i4O6&nbsp;</strong> (original encrypted SERVER#) as the hash to check and <strong style="background:#9F0;">&nbsp; W5xo#0CKN6$T4Gy_w8;CeU.rr)#e274UVY8Yl]n{e3H1T:W &nbsp;</strong> (SECRET1+SERVER#+SECRET2) as the string to check against, finally the tool will tell you both strings match, confirming that the SERVER# never changed.

</p>
<p>
Finally you sum the <strong>SERVER #</strong> and the <strong>PLAYER #</strong>, 27 + 12 = <strong>39</strong>, 39-37 = <strong>2</strong>, confirming the winning number was 2.
</p>

<h2>What happen if I insert an Invalid PLAYER #</h2>
<p>
<strong>PLAYER #</strong> should be a number between 0 and 37.
</p>
<p>
If by mistake or intentionally you insert a non numeric entry or a number lower or higher than the limits as the <strong>PLAYER #</strong>, our server will use <strong>0</strong> as your <strong>PLAYER #</strong>
</p>

    
</div>