<div class="dataTable_wrapper">

	<? 
	
	$slot = new multi_slot(0);
	$slot->set_reels_content();
	?>
    
    <h2>How does it work?</h2>
<p>
First of all you need to know that we have <a href="#result_table">a table of possible results</a> for each reel, that means that every time you spin, randomly we choose one of the results in this table.</p><p>* This table will not change so each position of the table will always have the same result.
</p>

<p>
To prove that neither you nor us can possibly know what position of the table will be choose to get a result, we use two different set of numbers, one generated from our server and the other generated by your browser (Can be edited manually if you want), the sum of this  numbers is used to get a result from the <a href="#result_table">results table</a>.
</p>

<h2>Details of the process</h2>

<p>Before each spin our server generates a set of 15 random numbers between 0 and 109 (<strong>SERVER #</strong>), this numbers are encrypted using 2 secret keys (<strong>SECRETS</strong>) and then is displayed to you (Find it at the top of your slot machine). At the same time your browser generates another set of 15 random numbers between 0 and 109 (<strong>PLAYER #</strong>) (this numbers can be edited by you, is located at the top of your slot machine). At the moment you make your spin, your browser will send the <strong>PLAYER #</strong> to our server, and then it will add the <strong>SERVER #</strong> to it, the final number will be used to get a result from the <a href="#result_table">results table</a> in the following way: the fisrt 3 numbers will determine first reel positions, next 3 numbers the second reel positions and so on, for example the numbers <strong>12,54,67,10,103,101,85,9,32,67,1,44,82,22,17</strong> will get positions <strong>12,54,67</strong> for reel 1, positions <strong>10,103,101</strong> for reel 2, positions <strong>85,9,32</strong> for reel 3, positions <strong>67,1,44</strong> for reel 4 and positions <strong>82,22,17</strong> for reel 5. Finally spin results will be displayed, including the <strong>SECRET KEYS</strong> used to encrypt the <strong>SERVER #</strong>, the <strong>SERVER #</strong> decrypted, the <strong>PLAYER #</strong> provided by you and the <strong>FINAL POSITIONS</strong> used to get the result, with this information you can verify that the 
<strong>SERVER #</strong> wasn't changed and that your spin result was completely random.</p>

<p>*If the sum of a pair of numbers are higher than 109, we will substract 109 to get a number between the limits, for example, 27 + 86 = 113, the result number will be 113 - 109 = <strong>4</strong></p>

<h3>How the SERVER # is encrypted?</h3>
<p>
The <strong>SERVER #</strong> is encrypted with the <strong>SECRET KEYS</strong> using the <strong>BCRYPT</strong> hashing function, the encryption is made in the following way: <strong>BCRYPT(SECRET1+SERVER#+SECRET2)</strong>
</p>
<h3>Example</h3>
<p>
- Before the spin you see at the <strong>NEXT SPIN</strong> area that <strong>SERVER #</strong> is <strong style="background:#9F0;">&nbsp;$2y$10$9xtmvEDwlhWf7DIWA6.iEeSjbjhZVwItHVqA5JeswP8.m9jToYqv.&nbsp;</strong> and you insert <strong>87,44,1,9,94,53,1,55,7,49,76,46,71,24,27</strong> as the <strong>PLAYER #</strong>.</p>
<p>
- After the spin you get as a result: <strong>SECRET1</strong>: <strong style="background:#9F0;">&nbsp;je*pzO#@6s&qVNw &nbsp;</strong>, <strong>SECRET2</strong>: <strong style="background:#9F0;">&nbsp;Cb,%l?SLvNw0S]}V*.P{&nbsp;</strong>, <strong>SERVER #</strong>: 55,68,61,89,76,58,18,20,17,18,102,41,85,82,86 , <strong>PLAYER #</strong>: 87,44,1,9,94,53,1,55,7,49,76,46,71,24,27, <strong>RESULT #</strong>: 33,3,62,98,61,2,19,75,24,67,69,87,47,106,4
</p>
<p>
- To verify that the <strong>SERVER #</strong> wasnt changed after the spin, you use any <a href="https://bcrypt-generator.com/" target="_blank">BCRYPT generator</a> and insert: 
<strong style="background:#9F0;">&nbsp;$2y$10$9xtmvEDwlhWf7DIWA6.iEeSjbjhZVwItHVqA5JeswP8.m9jToYqv.&nbsp;</strong> (original encrypted SERVER#) as the hash to check and <strong style="background:#9F0;">&nbsp; je*pzO#@6s&qVNw55,68,61,89,76,58,18,20,17,18,102,41,85,82,86Cb,%l?SLvNw0S]}V*.P{ &nbsp;</strong> (SECRET1+SERVER#+SECRET2) as the string to check against, finally the tool will tell you both strings match, confirming that the SERVER# never changed.

</p>
<p>
Finally you sum the <strong>SERVER #</strong> and the <strong>PLAYER #</strong>, (55,68,61,89,76,58,18,20,17,18,102,41,85,82,86) + (87,44,1,9,94,53,1,55,7,49,76,46,71,24,27) = <strong>33,3,62,98,61,2,19,75,24,67,69,87,47,106,4</strong>, and check the <a href="#result_table">results table</a> to confirm that the positions are the same result you got on the slot machine.
</p>

<h2>What happen if I insert an Invalid PLAYER #</h2>
<p>
<strong>PLAYER #</strong> should be a set of 15 integer numbers between 0 and 109, separate by comma.
</p>
<p>
If by mistake or intentionally you insert a non numeric entry or a number lower or higher than the limits as the <strong>PLAYER #</strong>, our server will use <strong>0</strong> as your <strong>PLAYER #</strong>
</p>

<h2>*DOES THE RESULTS TABLE EVER CHANGE?</h2>
<p>
The <strong>RESULTS TABLE</strong> is not meant to change, you can store a local copy of the <a href="#result_table">Results Table</a> to constantly verify that it haven't change.
</p>
<p>
However, it could be possible that we have to make some adjustments on the <strong>RESULTS TABLE</strong>, in this case, we will notify players in advance.
</p>


	<h2>Results Table <a id="result_table" name="result_table"></a> </h2>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Reel</th>
                <th>Position</th>
                <th>Symbol</th>
            </tr>
        </thead>
        <tbody>
            <? $i=1; $rnum = 1; foreach($slot->reels_content as $reel){ $i++; if($i%2){$class = "odd";}else{$class = "even";} ?>
				<? $pos = 0; foreach($reel as $symbol){ ?>
                    <tr class="<? echo $class ?>">
                        <td><? echo $rnum ?></td>
                        <td><? echo $pos ?></td>
                        <td><img src="https://play.casinogamesonline.com/utilities/games/multi_slot_alien/imgs/figures/<? echo $symbol ?>.png" width="50" height="50"></td>
                    </tr>
                <? $pos++; } $rnum++; ?>
            <? } ?>
            
        </tbody>
    </table>
    
</div>